version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      jupiter:
        patterns:
          - "*jupiter"
          - "jupiter*"
          - "*jupiter*"

  - package-ecosystem: "pip"
    directory: "/jeorg-python-algorithms/jeorg-python-alg1-hanoi-towers"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/jeorg-python-algorithms/jeorg-python-alg2-floyd-tortoise-hare"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/jeorg-python-algorithms/jeorg-python-alg3-brent"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/jeorg-javascript-algorithms/jeorg-javascript-alg2-floyd-tortoise-hare"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/jeorg-javascript-algorithms/jeorg-javascript-alg3-brent-tortoise-hare"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/jeorg-javascript-algorithms/jeorg-javascript-alg4-activity-selector"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/jeorg-javascript-algorithms/jeorg-javascript-alg-hanoi-towers"
    schedule:
      interval: "daily"
