version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: eclipse-temurin:21-alpine
    steps:
      - checkout

      - run: apk add maven
      - run: apk add make
      - run:
          name: Install Packages
          command:
              sudo apt update &&
              sudo apt-get -y install python3-pip &&
              sudo apt-get -y install npm &&
              sudo npm install --global yarn &&
              sudo npm install -g n &&
              sudo n 16

      - run:
          name: Python upgrade
          command:
              pip3 install coverage &&
              pip3 install pytest

      - run:
          name: Install Packages
          command: make install

      - run:
          name: Run Python And Node Tests
          command: make coverage

      - run:
          name: Compile
          command: mvn clean install
