version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: eclipse-temurin:21-alpine
    steps:
      - checkout

      - run: apk add maven
      - run: apk add make
      - run:
          name: Install Packages
          command:
            apk add python3 py3-pip &&
            apk add py3-virtualenv &&
            apk add nodejs &&
            apk add npm &&
            npm install -g yarn

      - run:
          name: Python upgrade
          command:
            python3 -m venv myenv &&
            source myenv/bin/activate &&
            pip3 install coverage &&
            pip3 install pytest

      - run:
          name: Install Packages
          command: make install

      - run:
          name: Run Python And Node Tests
          command: make coverage

      - run:
          name: Compile
          command: mvn clean install
