name: jeorg-algorithms-test-drives

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install Software
        run: sudo apt update -y &&
             apt install python3-pip -y &&
             pip3 install coverage &&
             pip3 install pytest

      - name: Build and Test Externals
        run:  make install

      - name: Coverage Externals
        run:  make coverage

      - name: Build and Test Maven
        run: mvn clean jacoco:prepare-agent install

      - name: Coverage Maven
        run: mvn jacoco:report

      - name: Report
        run: mvn omni-coveragereporter:report
        env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
           CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
